language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
install: true
script: 
  - mvn install
  #- mvn cobertura:cobertura
  - ls
after_success:
  - bash <(curl -s https://codecov.io/bash)
